# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 23:49
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

fixture = 'initial_data'

class Migration(migrations.Migration):
    def load_fixture(apps, schema_editor):
        call_command('loaddata', fixture, app_label='points')

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=load_fixture),
    ]
