# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 19:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='alias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='point',
            name='assigned_by',
            field=models.ForeignKey(default=datetime.datetime(2016, 5, 12, 19, 29, 21, 182052, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='assigned_to',
            field=models.ForeignKey(default=datetime.datetime(2016, 5, 12, 19, 29, 30, 881791, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='comment',
            field=models.CharField(default=datetime.datetime(2016, 5, 12, 19, 29, 40, 279606, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
