# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20160516_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ('-created',)},
        ),
    ]
